### ISSUE TITLE
Error update policy for  Anonymous Token

### ISSUE THREAD

**Issue by ihard** [jsundh/ansible-modules-consul-acl#2] opened 2019-12-29 17:01 UTC
During update policy for 'Anonymous Token', get error:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'policies'`

**Comment by jsundh** [comment] 2020-01-24 20:49
Likely a duplicate of #1, if it didn't have any policies attached to it. Try using 0.3.0 and see if it works now, otherwise reopen the issue again.

**Closed as completed by jsundh** 2020-01-24 20:49 UTC
